language: c
sudo: false

script:
  - build_platform uno
  - build_platform leonardo
  - build_platform zero
  - build_platform esp8266
notifications:
  email:
    on_success: change
    on_failure: change
